name: jsonable
description: Management and validator of JSON with dart classes, without generated code and without reflection.
author: "Spina Nico <spinanico93@gmail.com>"
repository: https://github.com/SpinaNico/jsonable
homepage: https://github.com/SpinaNico/jsonable

version: 0.2.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.8
  benchmark_harness: ^2.0.0
  coverage: ^1.0.3
