name: jsonable
description: Management and validator of JSON with dart classes, without generated code and without reflection.
author: "Spina Nico <spinanico93@gmail.com>"
repository: https://github.com/SpinaNico/jsonable
homepage: https://github.com/SpinaNico/jsonable

version: 0.1.1+3
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:  

dev_dependencies:
  test: any
  benchmark_harness: any
  test_coverage: ^0.3.0