name: jsonable
description: Simple package for converting Dart class to Json
author: "Spina Nico <spinanico93@gmail.com>"
repository: https://github.com/SpinaNico/jsonable
homepage: https://github.com/SpinaNico/jsonable

version: 0.0.2+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:  

dev_dependencies:
  test: any
  benchmark_harness: any
